---
title: "Dysautonomia - What's that?"
---

Hey thanks for reading this far! A major part of my life is dealing with a chronic illness and part of my mission as a researcher is to help spread awareness for dysautonomia. When I was in 7th grade I became sick with the flu and never really recovered. A few years later I was diagnosed with a condition called POTS (Postural Orthostatic Tachycardia Syndrome) a form of dysautonomia. Dysautonomia is an umbrella term for conditions affecting the autonomic nervous system. In the case of POTS, this manifests as fast heart rate when standing up. Everyone with POTS has different experiences, but for me it contributes to excessive fatigue, headaches, dizziness, temperature dysregulation, amongst a host of other symptoms.

POTS is significantly under researched and unfortunately there are currently no FDA approved medications to help manage the symptoms of POTS. I was fortunate to be able to advocate on capital hill as part of Dysautonomia International's Advocacy Day in 2023.

If you are at all interested in learning more about POTS or the research that needs to be done, please check out the links I have included below.

Dysautonomia International: <https://www.dysautonomiainternational.org/>

NIH NOSI: <https://grants.nih.gov/grants/guide/notice-files/NOT-HL-24-018.html>
